enabledWorlds:
  world:
    maxFallingBlocks: 12
    removeLandedBlocks: 5
  world_nether:
    excludedTypes:
    - FIREBALL
  world_the_end:
    excludedBlocks:
    - ENDER_STONE
excludedBlocks:
- BROWN_MUSHROOM
- CARPET
- CARROT
- COBBLE_WALL
- COCOA
- CROPS
- DEAD_BUSH
- DIODE_BLOCK_OFF
- DIODE_BLOCK_ON
- FENCE
- FENCE_GATE
- FIRE
- GLASS
- ICE
- IRON_FENCE
- LEAVES
- LONG_GRASS
- MELON_STEM
- NETHER_FENCE
- NETHER_WARTS
- POTATO
- PUMPKIN_STEM
- REDSTONE_COMPARATOR_OFF
- REDSTONE_COMPARATOR_ON
- REDSTONE_LAMP_OFF
- REDSTONE_LAMP_ON
- REDSTONE_TORCH_OFF
- REDSTONE_TORCH_ON
- REDSTONE_WIRE
- RED_MUSHROOM
- RED_ROSE
- SAPLING
- SKULL
- SNOW
- SPONGE
- STAINED_GLASS
- STAINED_GLASS_PANE
- STONE_PLATE
- SUGAR_CANE_BLOCK
- THIN_GLASS
- TORCH
- TRAP_DOOR
- TRIPWIRE
- VINE
- WATER_LILY
- WEB
- WOOD_PLATE
- YELLOW_FLOWER
maxFallingBlocks: 30
removeLandedBlocks: 0
